#!/bin/bash
cp -R lib /home/chronos/user/lib
cp -R bin /home/chronos/user/bin
cp -R vim /home/chronos/user/.vim
cp vimrc /home/chronos/user/.vimrc
cp bashrc /home/chronos/user/.bashrc
source .bashrc

